-- Ajusta refresh_tokens ao DER de autenticação.
-- Idempotente para permitir reaplicação segura.
ALTER TABLE public.refresh_tokens
    ALTER COLUMN user_id DROP IDENTITY IF EXISTS;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'refresh_tokens'
          AND column_name = 'token_id'
          AND is_identity = 'YES'
    ) THEN
        ALTER TABLE public.refresh_tokens
            ALTER COLUMN token_id ADD GENERATED BY DEFAULT AS IDENTITY;
    END IF;
END $$;

ALTER TABLE public.refresh_tokens
    ALTER COLUMN token_hash SET NOT NULL,
    ALTER COLUMN expire_at SET NOT NULL,
    ALTER COLUMN created_at SET DEFAULT NOW(),
    ALTER COLUMN created_at SET NOT NULL;

ALTER TABLE public.refresh_tokens
    DROP CONSTRAINT IF EXISTS refresh_tokens_user_id_fkey;

ALTER TABLE public.refresh_tokens
    ADD CONSTRAINT refresh_tokens_user_id_fkey
    FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON DELETE CASCADE;

CREATE UNIQUE INDEX IF NOT EXISTS uq_refresh_tokens_token_hash
    ON public.refresh_tokens (token_hash);

CREATE INDEX IF NOT EXISTS ix_refresh_tokens_user_id
    ON public.refresh_tokens (user_id);
