name: Validate PR to main

on:
  pull_request:
    branches:
      - main

jobs:
  validate-source:
    runs-on: ubuntu-latest

    steps:
      - name: Check source branch
        run: |
          if [ "${{ github.head_ref }}" != "develop" ]; then
            echo "PRs para main só podem vir da branch develop."
            exit 1
          fi
          